
TARGET = measure_bandw
$(TARGET):

#include makedefs
CCFILES = measure_bandw.cc

CCOBJS  = measure_bandw.o

MODULE		= 
LIBRARY		= 
MODULE_TARGET	= 


HDRS = 

commands_1.o: commands_1.cc
 
include ../Make2
