
TARGET = commands_1
$(TARGET):

#include makedefs
CCFILES = commands_1.cc

CCOBJS  = commands_1.o

MODULE		= commands_1
LIBRARY		= cmds
MODULE_TARGET	= $(OBJLIB_DIR)/$(MODULE)


HDRS = 

commands_1.o: commands_1.cc
 
include ../Make2
