
TARGET = bmm_semi_hsp
$(TARGET):

#include makedefs
CCFILES = bmm_semi_hsp.cc

CCOBJS  = bmm_semi_hsp.o

MODULE		= bsim3
LIBRARY		= dev
MODULE_TARGET	= $(OBJLIB_DIR)/$(MODULE)


HDRS = 

bmm_semi_hsp.o: bmm_semi_hsp.cc
 
include ../Make2
